version: '3'
services:
  web:
    container_name: app
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./:/app
    restart: always
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo/myapp
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
