version: '3'
services:
  web:
    container_name: app
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./:/app
    restart: always
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://root:root@mongo/myapp?authSource=admin
    links:
      - mongo
      - redis
      - graylog
  mongo:
    container_name: mongo
    image: mongo:4
    command: [--auth]
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./data:/data/redis
    ports:
      - 6379:6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/data/elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
  graylog:
    image: graylog/graylog:3.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_ROOT_USERBANE=anshu
      - GRAYLOG_REST_LISTEN_URI=http://127.0.0.1:9000/api/
      - GRAYLOG_REST_TRANSPORT_URI=http://127.0.0.1:9000/api/
      - GRAYLOG_WEB_LISTEN_URI=http://127.0.0.1:9000/
      - GRAYLOG_MONGODB_URI=mongodb://root:root@mongo/graylog?authSource=admin
    links:
      - mongo:mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - ./data:/data/graylog
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      - 5555:5555
